using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class ScoreboardModel
{
    [RealtimeProperty(1, true, true)]
    private string _scoreBoardText;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ScoreboardModel : RealtimeModel {
    public string scoreBoardText {
        get {
            return _scoreBoardTextProperty.value;
        }
        set {
            if (_scoreBoardTextProperty.value == value) return;
            _scoreBoardTextProperty.value = value;
            InvalidateReliableLength();
            FireScoreBoardTextDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ScoreboardModel model, T value);
    public event PropertyChangedHandler<string> scoreBoardTextDidChange;
    
    public enum PropertyID : uint {
        ScoreBoardText = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _scoreBoardTextProperty;
    
    #endregion
    
    public ScoreboardModel() : base(null) {
        _scoreBoardTextProperty = new ReliableProperty<string>(1, _scoreBoardText);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _scoreBoardTextProperty.UnsubscribeCallback();
    }
    
    private void FireScoreBoardTextDidChange(string value) {
        try {
            scoreBoardTextDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _scoreBoardTextProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _scoreBoardTextProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ScoreBoardText: {
                    changed = _scoreBoardTextProperty.Read(stream, context);
                    if (changed) FireScoreBoardTextDidChange(scoreBoardText);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _scoreBoardText = scoreBoardText;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
