using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class ScoreSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _playerScore;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ScoreSyncModel : RealtimeModel {
    public int playerScore {
        get {
            return _playerScoreProperty.value;
        }
        set {
            if (_playerScoreProperty.value == value) return;
            _playerScoreProperty.value = value;
            InvalidateReliableLength();
            FirePlayerScoreDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ScoreSyncModel model, T value);
    public event PropertyChangedHandler<int> playerScoreDidChange;
    
    public enum PropertyID : uint {
        PlayerScore = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _playerScoreProperty;
    
    #endregion
    
    public ScoreSyncModel() : base(null) {
        _playerScoreProperty = new ReliableProperty<int>(1, _playerScore);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _playerScoreProperty.UnsubscribeCallback();
    }
    
    private void FirePlayerScoreDidChange(int value) {
        try {
            playerScoreDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _playerScoreProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _playerScoreProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PlayerScore: {
                    changed = _playerScoreProperty.Read(stream, context);
                    if (changed) FirePlayerScoreDidChange(playerScore);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _playerScore = playerScore;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
